name: APK Yigici Murekkeb

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Python Qurasdir
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Android JDK və Alətləri Hazırla
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache git zlib1g-dev libssl-dev libffi-dev libgdbm-dev libncursesw5-dev libsqlite3-dev readline-common libbz2-dev xz-utils liblzma-dev togl tk-dev cython3 libgstreamer1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav libmtdev-dev xclip xsel libjpeg-dev
          pip install --upgrade pip
          pip install buildozer cython==0.29.33 kivy

      - name: Buildozer Ayarla və APK Çıxar
        run: |
          yes | buildozer init
          sed -i 's/source.include_exts = py,png,jpg,kv,atlas/source.include_exts = py,png,jpg,kv,atlas,txt/g' buildozer.spec
          sed -i 's/title = My Application/title = Kiber Akademiya/g' buildozer.spec
          sed -i 's/#android.accept_sdk_license = False/android.accept_sdk_license = True/g' buildozer.spec
          yes | buildozer -v android debug

      - name: Hazır APK Faylını Yüklə və Təhvil Ver
        uses: actions/upload-artifact@v4
        with:
          name: Kiber-Akademiya-Ugurla-Yigildi
          path: bin/*.apk
