name: APK Yigici

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Python Qurasdir
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Kitabxanalari Yukle
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libssl-dev cmake libgdbm-dev libgdbm-compat-dev liblzma-dev libreadline-gplv2-dev libsqlite3-dev tk-dev uuid-dev libffi-dev lld
          pip install --upgrade pip
          pip install buildozer cython==0.29.33 kivy

      - name: APK Yig
        run: |
          yes | buildozer init
          sed -i 's/source.include_exts = py,png,jpg,kv,atlas/source.include_exts = py,png,jpg,kv,atlas,txt/g' buildozer.spec
          sed -i 's/title = My Application/title = Kiber Akademiya/g' buildozer.spec
          yes | buildozer -v android debug

      - name: APK-ni Yukle
        uses: actions/upload-artifact@v3
        with:
          name: Kiber-Akademiya-APK
          path: bin/*.apk
